language: node_js
os:
  - windows
dist: trusty
sudo: true
services:
  - docker
before_install:
  - docker build -t souravdeveloper/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true souravdeveloper/docker-react npm run test
