language: node_js
node_js:
  - 14.15.1
services:
  - docker
before_install:
  - docker build -t souravdeveloper/docker-react -f Dockerfile.dev .
script:
  - docker run souravdeveloper/docker-react npm run test -- --coverage
