language: node_js
node_js:
  - 14.15.1
cache: npm
services:
  - docker
before_install:
  - docker build -t souravdeveloper/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true souravdeveloper/docker-react npm run test
