language: node_js
node_js:
  - 14.15.1
services:
  - docker
before_install:
  - npm install -g
  - docker build -t souravdeveloper/docker-react -f Dockerfile.dev .
script:
  - docker run souravdeveloper/docker-react npm  test -- --coverage
